name = "pgshims"
main = "dist-cf/index.js"
compatibility_date = "2022-10-19"
node_compat = false

[build]
watch_dir = "shims"
command = "./build.sh"

[vars]
# DATABASE_URL
# Run `wrangler secret put DATABASE_URL` and enter the connection string when prompted.
# And/or for `wrangler dev --local`: create `.dev.vars` containing `DATABASE_URL=mysecretconnstr`.
