name = "pgshims"
main = "dist-cf/index.js"
compatibility_date = "2022-10-19"
node_compat = false

[build]
watch_dir = "shims"
command = """( \
  echo "import tlsWasm from '../shims/net/tls.wasm';" \
  && npx esbuild index.ts --external:pg-native --inject:shims/shims.js --bundle --format=esm --minify \
  ) > dist-cf/index.js"""

[vars]
# DATABASE_URL
# Run `wrangler secret put DATABASE_URL` and enter the connection string when prompted.
# And/or for `wrangler dev --local`: create `.dev.vars` containing `DATABASE_URL=mysecretconnstr`.
